### ISSUE TITLE
Error in Compilation "  Class mikehaertl\wkhtmlto\Pdf does not exist "

### ISSUE THREAD

**Issue by sreenathnr** [mikehaertl/phpwkhtmltopdf#323]
# Compilation Problems
* Compilation breaks in Magento 2.3.2 and got the error 
`  Class mikehaertl\wkhtmlto\Pdf does not exist  
`
It was working in Magento 2.3.1 and I upgrade Magento to 2.3.2. After that, I got the compilation error.
### Preconditions

   1. Magento CE 2.3.2 without sample data is installed.
   2. used the class by  `use mikehaertl\wkhtmlto\Pdf;`

### Result
- The compilation broke and seems the error message

```
Compilation was started.
Area configuration aggregation... 5/7 [====================>-------]  71% 41 secs 298.0 MiB
In ClassReader.php line 35:
                                                        
  Class mikehaertl\wkhtmlto\Pdf does not exist  
                                                        

In ClassReader.php line 29:

```

**Comment by mikehaertl** [comment]
This must be a problem with PHP autoloader. If autoloading doesn't work correctly with Magento you need to find out what they messed up. I can not help you with this and it's not a bug in our library.
